### ISSUE TITLE
Hey, which dataset do you use to convert kitti velodyne odometry dataset to a rosbag?

### ISSUE THREAD

**Issue by bzdfzfer** [stevenliu216/568-Final-Project#1]
Hi! I downloaded the kitti08 rosbag you converted and found that this bag is motion compensated. Could you share me the link of the source data you used to get this bag? Thanks.

**Comment by stevenliu216** [comment]
Hello!

It is sequence 08 of the KITTI odometry evaluation dataset, which you can find the raw data from here:
http://www.cvlibs.net/datasets/kitti/raw_data.php?type=residential

Look for "2011_09_30_drive_0028" and you should be able to find un-synced data.  Keep in mind that the ground truth is only provided for timestamps 1100 to 5170.

**Comment by bzdfzfer** [comment]
thanks  a lot for your help!
