### ISSUE TITLE
matlab evaluation issues

### ISSUE THREAD

**Issue by goldenminerlmg** [stevenliu216/568-Final-Project#3]
Hi author!
  When I use the matlab script "benchmarking.m", I am not clear about how to use it. Kitti odometry benchmark's data seems like:
1.000000e+00 9.043680e-12 2.326809e-11 5.551115e-17 9.043683e-12 1.000000e+00 2.392370e-10 3.330669e-16 2.326810e-11 2.392370e-10 9.999999e-01 -4.440892e-16
9.999978e-01 5.272628e-04 -2.066935e-03 -4.690294e-02 -5.296506e-04 9.999992e-01 -1.154865e-03 -2.839928e-02 2.066324e-03 1.155958e-03 9.999971e-01 8.586941e-01
9.999910e-01 1.048972e-03 -4.131348e-03 -9.374345e-02 -1.058514e-03 9.999968e-01 -2.308104e-03 -5.676064e-02 4.128913e-03 2.312456e-03 9.999887e-01 1.716275e+00
.......
which are the first three rows (3X4) of the transformation matrix (4X4). But the "FILENAME.txt" only provide data like this:
x: 0.0234626941383
y: -0.236314684153
z: -0.222662851214
---
x: 0.0471226125956
y: -0.298985630274
z: -0.230534926057
---
x: 0.0593420229852
y: -0.306566476822
z: -0.102495282888
.......
So I am not sure how the script deal with these two different data types. Can you give more detailed description on how to use it ?
Thanks very much!

**Comment by stevenliu216** [comment]
Hello, for this project's purposes, we simplified the evaluation by only considering x,y, and the orientation calculated from those two coordinates. 

Additionally, the LOAM algorithm does not handle global localization, so the output results will not be with respect to the world frame. To properly evaluate the results with KITTI ground truth, we mapped LOAM results back into the world frame with the benchmarking.m script.

**Comment by HongweiSunny** [comment]
Hello, author.
I read your code in benchmarking.m and I do not understand the matrix R in following code:
*******code:
if translateAndRotate == 1
    deltaLength = length(position)-length(groundTruth);
    %apply rotation to true x and y coordinates (x and z in file)
    i = 1;
    while i <= length(position)
        temp = [position(i,1) position(i,3)]***R**;
        convertPosition(i,1) = -temp(1); %negative needed to flip x
        convertPosition(i,2) = temp(2);
        i = i + 1;
    end
So why the position that I get from loam need to multiply R?
and is R constant for every sequences?
