### ISSUE TITLE
Exporting(saving) whole map

### ISSUE THREAD

**Issue by space03** [stevenliu216/568-Final-Project#5]
Hi. I'm a master candidate student. I'm not good at ROS.

For testing velodyne lidar 3D SLAM(LOAM), I stuck in problem.
I want to save and export the whole map.

what i have done is recording my surrounding in rosbag files. and setup the loam.
1st terminal : roslaunch loam_velodyne loam_velodyne.launch
2nd terminal : rosbag play MY_BAG_FILE.bag

but I cannot export the result map. 
I found the comment "rosrun pcl_ros pointcloud_to_pcd input:=/velodyne_cloud_registered" is the solution but it just gave me only current window saving. 

How can i do for exporting and saving the map?

Please help me.
@stevenliu216

**Comment by stevenliu216** [comment]
Hi, sure I can help you. By "exporting the whole map" do you want the registered point clouds of the entire KITTI sequence? 

In your current approach, you could play around with the rviz settings. Look for one called "delay" under the pointcloud2 display type for `/velodyne_cloud_registered`. Its default setting of 0 will cause older point clouds to disappear. Set it to a higher number like 100000 and you'll be able to save more point clouds. Your computer will run slower as well. 

I would also recommend you to check out other ROS offered tools like [bag_to_pcd tool instead.](http://wiki.ros.org/pcl_ros#bag_to_pcd) Record a new bag file of the `/velodyne_cloud_registered` topic and run this tool on it, which will you a pcd file output as well.
